[package]
name = "rust-gtk-app"
version = "0.1.0"
edition = "2018"

[dependencies]
gtk = "0.18.1"
gio = "0.20.0"
glib = "0.10.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.6"
futures = "0.3"

[[bin]]
name = "rust-gtk-app"
path = "src/main.rs"
