[package]
name = "rust-gtk-app"
version = "0.1.0"
edition = "2018"

[dependencies]
gtk = "0.18.1"
glib = "0.18.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"

[[bin]]
name = "rust-gtk-app"
path = "src/main.rs"
