name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpango1.0-dev
        sudo apt-get install -y libcairo2-dev
        sudo apt-get install -y libatk1.0-dev
        sudo apt-get install -y libgdk-pixbuf2.0-dev
        sudo apt-get install -y libgtk-3-dev
        sudo apt-get install -y libsoup2.4-dev
        sudo apt-get install -y libjavascriptcoregtk-4.1-dev
        sudo apt-get install -y libwebkit2gtk-4.0-dev


    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
